
spring:
  liquibase:
    change-log: classpath:dbchangelog.xml
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
log4j.logger.org.hibernate.SQL: debug

